name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: '30'

jobs:
  Explore-GitHub-Actions:
    runs-on:
      - self-hosted
      - Linux
    timeout-minutes: 10 # Increase the timeout to a suitable value
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
        timeout-minutes: 30
      - name: Run the Maven to package the application
        run: mvn clean install
      - name: Copy JAR for staging folder
        run: mkdir staging && cp target/*.jar staging
#      - name: Archive code
#        uses: actions/upload-artifact@v3
#        with:
#          name: Package
#          path: staging
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ env.USERNAME }}
#          password: ${{ env.PASSWORD }}
#      - name: Build and push Docker images with Dockerfile
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/prometheus-grafana:latest
#      - name: Pull Docker Image
#        run: docker pull nlthanhcse/prometheus-grafana:latest
#      - name: Run Docker Container
#        run: docker run -d --name prometheus-grafana -p 9999:9999 prometheus-grafana:latest
      - name: Start External Applications with Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d