name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Run the Maven to package the application
        run: mvn clean install
      - name: Copy JAR for staging folder
        run: mkdir staging && cp target/*.jar staging
      - name: Archive code
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging